services:
  app:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.prod
    container_name: mini-trello-app
    restart: unless-stopped
    volumes:
      - "./:/var/www/html"
      - "./database:/var/www/html/database"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
    networks:
      - mini-trello-network
  nginx:
    image: "nginx:1.25-alpine"
    container_name: mini-trello-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - "./:/var/www/html:ro"
      - "./docker/nginx/simple.conf:/etc/nginx/conf.d/default.conf:ro"
    depends_on:
      - app
    networks:
      - mini-trello-network
networks:
  mini-trello-network:
    driver: bridge
